server:
  servlet:
    context-path: /bookms
  port: 8888

spring:
  application:
    name: book-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8070
      label: main

  datasource:
    url: jdbc:h2:mem:books-db
    username: booksapp
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect